/**
 * useWorkflowArtifacts Hook
 * Monitor artifact generation and updates from workflow events
 *
 * Features:
 * - Track artifacts by node name
 * - Update as they're generated (from node 'end' events)
 * - Provide access to latest versions
 * - Handle missing/incomplete artifacts
 * - Convenience accessors for common artifacts
 * - Memoized artifact extraction
 *
 * Phase 2, Task 2.3
 */

import { useMemo } from 'react';
import { useWorkflowEvents } from './useWorkflowEvents';
import { WorkflowNode } from '@/types/api';

/**
 * Style specification artifact
 */
export interface StyleSpec {
  genre?: string;
  subgenres?: string[];
  bpm?: number;
  key?: string;
  mood?: string[];
  instrumentation?: string[];
  vocal_style?: string;
  tags?: string[];
  [key: string]: unknown;
}

/**
 * Lyrics specification artifact
 */
export interface LyricsSpec {
  sections?: Array<{
    type: string;
    lines: string[];
    metadata?: Record<string, unknown>;
  }>;
  full_text?: string;
  rhyme_scheme?: string;
  citations?: Array<{
    source_id: string;
    chunk_hash: string;
    weight: number;
  }>;
  [key: string]: unknown;
}

/**
 * Producer notes artifact
 */
export interface ProducerNotesSpec {
  arrangement?: string;
  structure?: string;
  mix_targets?: Record<string, unknown>;
  production_notes?: string[];
  [key: string]: unknown;
}

/**
 * Workflow artifacts return value
 */
export interface WorkflowArtifacts {
  /** Style specification (from STYLE node) */
  style: StyleSpec | null;
  /** Lyrics specification (from LYRICS node) */
  lyrics: LyricsSpec | null;
  /** Producer notes (from PRODUCER node) */
  producerNotes: ProducerNotesSpec | null;
  /** Composed prompt (from COMPOSE node) */
  composedPrompt: string | null;
  /** All artifacts mapped by node name */
  allArtifacts: Partial<Record<WorkflowNode, any>>;
  /** Is loading (reflects event loading state) */
  isLoading: boolean;
}

/**
 * Monitor workflow artifact generation
 *
 * Extracts and tracks artifacts as they're generated by workflow nodes.
 * Artifacts are extracted from 'end' phase events' data.artifacts field.
 *
 * @example
 * ```tsx
 * const artifacts = useWorkflowArtifacts('run-123');
 *
 * if (artifacts.isLoading) {
 *   return <Spinner />;
 * }
 *
 * return (
 *   <div>
 *     {artifacts.style && (
 *       <StyleCard style={artifacts.style} />
 *     )}
 *     {artifacts.lyrics && (
 *       <LyricsDisplay lyrics={artifacts.lyrics} />
 *     )}
 *     {artifacts.composedPrompt && (
 *       <PromptPreview prompt={artifacts.composedPrompt} />
 *     )}
 *   </div>
 * );
 * ```
 */
export function useWorkflowArtifacts(runId: string): WorkflowArtifacts {
  const { events, isLoading } = useWorkflowEvents(runId);

  /**
   * Extract artifacts from events
   * Memoized to prevent recalculation on every render
   */
  const artifacts = useMemo<Omit<WorkflowArtifacts, 'isLoading'>>(() => {
    // Map to store latest artifact for each node
    const allArtifacts: Partial<Record<WorkflowNode, any>> = {};

    // Process events in chronological order
    // Later events for the same node will override earlier ones
    for (const event of events) {
      const { node_name, phase, data } = event;

      // Only process 'end' phase events (successful completion)
      if (!node_name || phase !== 'end') {
        continue;
      }

      const nodeName = node_name as WorkflowNode;

      // Extract artifacts from event data
      // Artifacts can be in data.artifacts or data.output depending on node
      const artifactData = data.artifacts || data.output || null;

      if (artifactData) {
        allArtifacts[nodeName] = artifactData;
      }
    }

    // Extract common artifacts with type safety
    const style = (allArtifacts[WorkflowNode.STYLE] as StyleSpec) || null;
    const lyrics = (allArtifacts[WorkflowNode.LYRICS] as LyricsSpec) || null;
    const producerNotes =
      (allArtifacts[WorkflowNode.PRODUCER] as ProducerNotesSpec) || null;

    // Composed prompt is typically a string in COMPOSE node output
    let composedPrompt: string | null = null;
    const composeArtifact = allArtifacts[WorkflowNode.COMPOSE];
    if (composeArtifact) {
      // Handle different possible formats
      if (typeof composeArtifact === 'string') {
        composedPrompt = composeArtifact;
      } else if (composeArtifact.prompt) {
        composedPrompt = composeArtifact.prompt;
      } else if (composeArtifact.composed_prompt) {
        composedPrompt = composeArtifact.composed_prompt;
      }
    }

    return {
      style,
      lyrics,
      producerNotes,
      composedPrompt,
      allArtifacts,
    };
  }, [events]);

  return {
    ...artifacts,
    isLoading,
  };
}
