import React from 'react';

import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';

import { useWorkflowRuns } from '@/hooks/api/useWorkflows';
import { storiesApi } from '@/lib/api/stories';
import type { SongStory } from '@/types/api';

import { SongStoryPanel } from '../SongStoryPanel';


jest.mock('@/lib/api/stories', () => ({ storiesApi: { list: jest.fn(), get: jest.fn(), create: jest.fn(), update: jest.fn(), createMotif: jest.fn(), updateMotif: jest.fn(), listMotifs: jest.fn() }, StoryRevisionConflictError: class StoryRevisionConflictError extends Error { current_revision = 4; } }));
jest.mock('@/hooks/api/useWorkflows', () => ({ useWorkflowRuns: jest.fn() }));
const story: SongStory = { id: 'story-1', song_id: 'song-1', take_id: 'run-1', title: 'Memory', body_text: 'first line\n  second line', revision: 1, motifs: [], created_at: '', updated_at: '' };
const renderPanel = () => { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={client}><SongStoryPanel songId="song-1" /></QueryClientProvider>); };
beforeEach(() => { jest.clearAllMocks(); (useWorkflowRuns as jest.Mock).mockReturnValue({ data: { items: [{ id: 'run-1', song_id: 'song-1', status: 'completed' }] } }); (storiesApi.list as jest.Mock).mockResolvedValue([story]); });

it('renders existing story text verbatim, take link and run choices', async () => { renderPanel(); expect(await screen.findByText((_, node) => node?.textContent === 'first line\n  second line')).toBeInTheDocument(); expect(screen.getByText(/run-1 \(completed\)/)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Edit story' })); expect(screen.getAllByRole('option', { name: /run-1/ }).length).toBeGreaterThan(0); expect(screen.getAllByRole('option', { name: 'No take' }).length).toBeGreaterThan(0); });
it('creates with title, body and selected take', async () => { (storiesApi.create as jest.Mock).mockResolvedValue(story); const { container } = renderPanel(); await screen.findByText('Memory'); fireEvent.change(container.querySelector('#new-story-title')!, { target: { value: 'New' } }); fireEvent.change(container.querySelector('#new-story-body')!, { target: { value: 'Words' } }); fireEvent.change(container.querySelector('#new-story-take')!, { target: { value: 'run-1' } }); fireEvent.click(screen.getByRole('button', { name: 'Create story' })); await waitFor(() => expect(storiesApi.create).toHaveBeenCalledWith('song-1', { title: 'New', body_text: 'Words', take_id: 'run-1' })); });
it('updates expected revision and displays returned revision', async () => { const updated = { ...story, revision: 2, title: 'Changed' }; (storiesApi.update as jest.Mock).mockResolvedValue(updated); (storiesApi.list as jest.Mock).mockResolvedValueOnce([story]).mockResolvedValue([updated]); const { container } = renderPanel(); fireEvent.click(await screen.findByRole('button', { name: 'Edit story' })); fireEvent.change(container.querySelector('#story-story-1-title')!, { target: { value: 'Changed' } }); fireEvent.click(screen.getByRole('button', { name: 'Save story' })); await waitFor(() => expect(storiesApi.update).toHaveBeenCalledWith('song-1', 'story-1', expect.objectContaining({ expected_revision: 1, title: 'Changed' }))); expect(await screen.findByText(/Revision 2/)).toBeInTheDocument(); });
it('shows revision conflict and preserves typed text', async () => { (storiesApi.update as jest.Mock).mockRejectedValue(new Error('This story changed elsewhere (now revision 4). Reload to continue.')); const { container } = renderPanel(); fireEvent.click(await screen.findByRole('button', { name: 'Edit story' })); const input = container.querySelector('#story-story-1-body')!; fireEvent.change(input, { target: { value: 'My unsaved draft' } }); fireEvent.click(screen.getByRole('button', { name: 'Save story' })); expect(await screen.findByRole('alert')).toHaveTextContent('This story changed elsewhere (now revision 4). Reload to continue.'); expect(input).toHaveValue('My unsaved draft'); expect(screen.getByRole('button', { name: 'Reload' })).toBeInTheDocument(); });
it('creates and edits motifs', async () => { (storiesApi.createMotif as jest.Mock).mockResolvedValue({ id: 'motif-1' }); (storiesApi.updateMotif as jest.Mock).mockResolvedValue({}); renderPanel(); await screen.findByText('Memory'); fireEvent.change(screen.getByLabelText('Motif label'), { target: { value: 'Hook' } }); fireEvent.change(screen.getByLabelText('Notes'), { target: { value: 'note' } }); fireEvent.change(screen.getByLabelText('Start seconds (optional)'), { target: { value: '2.5' } }); fireEvent.click(screen.getByRole('button', { name: 'Add motif' })); await waitFor(() => expect(storiesApi.createMotif).toHaveBeenCalledWith('song-1', 'story-1', expect.objectContaining({ label: 'Hook', anchor: { start_seconds: 2.5 } }))); });
it('edits an existing motif with its expected revision', async () => { (storiesApi.list as jest.Mock).mockResolvedValue([{ ...story, motifs: [{ id: 'motif-1', story_id: 'story-1', song_id: 'song-1', take_id: null, label: 'Theme', notes: 'Old', anchor: null, revision: 3, created_at: '', updated_at: '' }] }]); (storiesApi.updateMotif as jest.Mock).mockResolvedValue({}); const { container } = renderPanel(); fireEvent.click(await screen.findByRole('button', { name: 'Edit motif' })); fireEvent.change(container.querySelector('#motif-1-label')!, { target: { value: 'New theme' } }); fireEvent.click(screen.getByRole('button', { name: 'Save motif' })); await waitFor(() => expect(storiesApi.updateMotif).toHaveBeenCalledWith('song-1', 'story-1', 'motif-1', expect.objectContaining({ expected_revision: 3, label: 'New theme' }))); });
it('shows empty state', async () => { (storiesApi.list as jest.Mock).mockResolvedValue([]); renderPanel(); expect(await screen.findByText(/No stories yet/)).toBeInTheDocument(); });
